name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Afficher un message
        run: echo "La CI fonctionne !"