name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier index.html
        run: run: test -f index.html

      - name: Afficher un message
        run: echo "Tous les tests sont réussis !"